# 【問題1】train_test_split のスクラッチ

In [1]:
#モジュールをインポート
import numpy as np
import math
import random
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
import warnings #ワーニング関連のモジュール？
warnings.filterwarnings('ignore') #ワーニングが消える？

In [2]:
# scikit-learnの train_test_split をスクラッチしてみます

def scratch_train_test_split(X, y, train_size=0.8):
    """検証データを分割する。
    引数
    ----------
    X : ndarray
      訓練データ (n_samples, n_features)
    y : ndarray
      正解値 (n_samples,)
    train_size : float
      何割をtrainとするか指定 (0 < train_size < 1)
    
    戻り値
    -------
    X_train : ndarray
      訓練データ (n_samples, n_features)
    X_test : ndarray
      検証データ (n_samples, n_features)
    y_train : ndarray
      訓練データの正解値 (n_samples,)
    y_test : ndarray
      検証データの正解値 (n_samples,)
    """
    # ここにコードを書く
    
    #配列の要素数を調べる
    #要素数と同じ長さのリストを作成
    #ランダムにリストの値を＊train_size分だけtrain（リスト）にしまう
    #for文でXとyのインデックスと照らし合わせてX_trainとy_trainに抽出
    #残りをX_testとy_testに代入
    #train_size=0.7
    #print(train_size)
    #n = int(100)   
    X = np.array(X)
    y = np.array(y)
    n = int(len(y))                                  #100と仮定した時
    count = list(range(n))                           #0から99までの100のリストができる
    train = random.sample(count,int(n*train_size))   #0.7と仮定すると70が入る、ランダムでtrainに70入る
    text = list(set(count)-set(train))               #100から70をひいた30がリストに入る
    #print(train[5])
    X_train = []
    y_train = []
    for i in range(int(n*train_size)):    #ランダムで入っている数字をインデックスに当てながら、for文で
        X_train.append(X[train[i]])       #X_trainとy_trainに加えていく
        y_train.append(y[train[i]])
    X_test = []
    y_test = []
    for j in range(int(n*(1-train_size)+1)):  #ランダムで入っている数字をインデックスに当てながら、for文で
        X_test.append(X[text[j]])           #X_testとy_testに加えていく
        y_test.append(y[text[j]])
    
    X_train = np.array(X_train)      #全ての配列を一律にnp配列に返還
    y_train = np.array(y_train)
    X_test = np.array(X_test)
    y_test = np.array(y_test)
    
    pass
    return X_train, X_test, y_train, y_test

In [3]:
'''
プロトタイプ
'''

# train_size=0.7
# print(train_size)
# n = int(100)   
# #n = int(len(y))                           #100と仮定
# count = list(range(n))
# print(count)
# train = random.sample(count,int(n*train_size)) #0.7と仮定すると70が入る
# print(train)
# text = list(set(count)-set(train))
# print(train[5])
# print(n*train_size)
# X_train = []
# y_train = []
# for i in range(int(n*train_size)):    #ランダムで入っている数字をインデックスに当てながら、for文で
#     X_train.append(X[train[i]])       #X_trainとy_trainに加えていく
#     y_train.append(y[train[i]])
# X_test = []
# y_test = []
# for j in range(int(n*(1-train_size))):  #ランダムで入っている数字をインデックスに当てながら、for文で
#     X_test.append(X[text[j]])           #X_testとy_testに加えていく
#     y_test.append(y[text[j]])
    
# print(count)
# print(type(count))
#print(train)
# print(len(train))
#print(text)
# print(X_train)
# print(y_train)

'\nプロトタイプ\n'

# 【問題2】 分類問題を解くコードの作成

 3種類の手法で3種類のデータセットを学習・推定するコードを作成

**ホールドアウト法で構わない**

- irisデータセット
    - ロジスティック回帰
    - SVM
    - 決定木
- シンプルデータセット1
    - ロジスティック回帰
    - SVM
    - 決定木
- シンプルデータセット2
    - ロジスティック回帰
    - SVM
    - 決定木

## アヤメ

In [4]:
#アヤメのデータを取得
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
X = pd.DataFrame(iris.data,columns=["sepal_length","sepal_width","petal_length","petal_width"] )
Y = pd.DataFrame(iris.target,columns=["Species"])
df = pd.concat([X,Y],axis=1)

# .queryで行抽出、locで列抽出する。
df_selected = df.query("Species == [1, 2]")
df_selected

sepal_length  sepal_width  petal_length  petal_width  Species
50            7.0          3.2           4.7          1.4        1
51            6.4          3.2           4.5          1.5        1
52            6.9          3.1           4.9          1.5        1
53            5.5          2.3           4.0          1.3        1
54            6.5          2.8           4.6          1.5        1
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[100 rows x 5 columns]

In [5]:
X_train, X_test, y_train, y_test = scratch_train_test_split(df_selected.iloc[:, :-1], df_selected.loc[:, "Species"], train_size=0.8)
print("X_train.shape : {}, X_test.shape : {}".format(X_train.shape, X_test.shape))

X_train.shape : (80, 4), X_test.shape : (20, 4)


In [6]:
# 評価する関数を作成する
def eval(y_true, y_pred):
    """
    2値分類の評価指標を計算する
    """
    acc = metrics.accuracy_score(y_true, y_pred)
    precision = metrics.precision_score(y_true, y_pred)
    recall = metrics.recall_score(y_true, y_pred)
    f1 = metrics.f1_score(y_true, y_pred)
    confusion = metrics.confusion_matrix(y_true, y_pred)
    return acc, precision, recall, f1, confusion

### ロジスティック回帰

In [7]:
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn import metrics

clf = make_pipeline(StandardScaler(),SGDClassifier(max_iter=1000, tol=1e-3,loss="log"))

# 学習する
clf.fit(X_train,y_train)
# 予測する
y_pred_clf = clf.predict(X_test)

print("acc : {}\nprecision : {}\nrecall : {}\nf1 : {}\nconfusion matrix \n {}".format(*eval(y_test, y_pred_clf)))



acc : 0.95
precision : 1.0
recall : 0.9090909090909091
f1 : 0.9523809523809523
confusion matrix 
 [[10  1]
 [ 0  9]]


### SVM

In [8]:
from sklearn.svm import SVC

svc = make_pipeline(StandardScaler(), SVC(gamma='auto'))

# 学習する
svc.fit(X_train,y_train)
# 予測する
y_pred_svc = svc.predict(X_test)

print("acc : {}\nprecision : {}\nrecall : {}\nf1 : {}\nconfusion matrix \n {}".format(*eval(y_test, y_pred_svc)))


acc : 0.95
precision : 1.0
recall : 0.9090909090909091
f1 : 0.9523809523809523
confusion matrix 
 [[10  1]
 [ 0  9]]


### 決定木

In [9]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(random_state=0)

# 学習する
tree.fit(X_train,y_train)
# 予測する
y_pred_tree = tree.predict(X_test)

print("acc : {}\nprecision : {}\nrecall : {}\nf1 : {}\nconfusion matrix \n {}".format(*eval(y_test, y_pred_tree)))


acc : 0.9
precision : 1.0
recall : 0.8181818181818182
f1 : 0.9
confusion matrix 
 [[9 2]
 [0 9]]


## シンプルデータ１

In [10]:
np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0,0.8], [0.8, 1.0]]
f0 = np.random.multivariate_normal(f0, cov, n_samples // 2)
f1 = np.random.multivariate_normal(f1, cov, n_samples // 2)
X_1 = np.concatenate([f0, f1])
y_1 = np.concatenate([
    np.full(n_samples // 2, 1),
    np.full(n_samples // 2, -1)
])

In [11]:
X_train_1, X_test_1, y_train_1, y_test_1 = scratch_train_test_split(X_1,y_1,train_size=0.8)
print("X_train_1.shape : {}, X_test_1.shape : {}".format(X_train_1.shape, X_test_1.shape))

X_train_1.shape : (400, 2), X_test_1.shape : (100, 2)


### ロジスティック回帰

In [12]:
clf_1 = make_pipeline(StandardScaler(),SGDClassifier(max_iter=1000, tol=1e-3,loss="log"))

# 学習する
clf_1.fit(X_train_1,y_train_1)
# 予測する
y_pred_clf_1 = clf_1.predict(X_test_1)

print("acc : {}\nprecision : {}\nrecall : {}\nf1 : {}\nconfusion matrix \n {}".format(*eval(y_test_1, y_pred_clf_1)))


acc : 1.0
precision : 1.0
recall : 1.0
f1 : 1.0
confusion matrix 
 [[42  0]
 [ 0 58]]


### SVM

In [13]:
svc_1 = make_pipeline(StandardScaler(), SVC(gamma='auto'))

# 学習する
svc_1.fit(X_train_1,y_train_1)
# 予測する
y_pred_svc_1 = svc_1.predict(X_test_1)

print("acc : {}\nprecision : {}\nrecall : {}\nf1 : {}\nconfusion matrix \n {}".format(*eval(y_test_1, y_pred_svc_1)))


acc : 1.0
precision : 1.0
recall : 1.0
f1 : 1.0
confusion matrix 
 [[42  0]
 [ 0 58]]


### 決定木

In [14]:
tree_1 = DecisionTreeClassifier(random_state=0)

# 学習する
tree_1.fit(X_train_1,y_train_1)
# 予測する
y_pred_tree_1 = tree_1.predict(X_test_1)

print("acc : {}\nprecision : {}\nrecall : {}\nf1 : {}\nconfusion matrix \n {}".format(*eval(y_test_1, y_pred_tree_1)))


acc : 1.0
precision : 1.0
recall : 1.0
f1 : 1.0
confusion matrix 
 [[42  0]
 [ 0 58]]


## シンプルデータ２

In [15]:
X_2 = np.array([
    [-0.44699 , -2.8073  ],[-1.4621  , -2.4586  ],
    [ 0.10645 ,  1.9242  ],[-3.5944  , -4.0112  ],
    [-0.9888  ,  4.5718  ],[-3.1625  , -3.9606  ],
    [ 0.56421 ,  0.72888 ],[-0.60216 ,  8.4636  ],
    [-0.61251 , -0.75345 ],[-0.73535 , -2.2718  ],
    [-0.80647 , -2.2135  ],[ 0.86291 ,  2.3946  ],
    [-3.1108  ,  0.15394 ],[-2.9362  ,  2.5462  ],
    [-0.57242 , -2.9915  ],[ 1.4771  ,  3.4896  ],
    [ 0.58619 ,  0.37158 ],[ 0.6017  ,  4.3439  ],
    [-2.1086  ,  8.3428  ],[-4.1013  , -4.353   ],
    [-1.9948  , -1.3927  ],[ 0.35084 , -0.031994],
    [ 0.96765 ,  7.8929  ],[-1.281   , 15.6824  ],
    [ 0.96765 , 10.083   ],[ 1.3763  ,  1.3347  ],
    [-2.234   , -2.5323  ],[-2.9452  , -1.8219  ],
    [ 0.14654 , -0.28733 ],[ 0.5461  ,  5.8245  ],
    [-0.65259 ,  9.3444  ],[ 0.59912 ,  5.3524  ],
    [ 0.50214 , -0.31818 ],[-3.0603  , -3.6461  ],
    [-6.6797  ,  0.67661 ],[-2.353   , -0.72261 ],
    [ 1.1319  ,  2.4023  ],[-0.12243 ,  9.0162  ],
    [-2.5677  , 13.1779  ],[ 0.057313,  5.4681  ],
])
y_2 = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
X_train_2, X_test_2, y_train_2, y_test_2 = scratch_train_test_split(X_2,y_2,train_size=0.8)
print("X_train_2.shape : {}, X_test_2.shape : {}".format(X_train_2.shape, X_test_2.shape))
print(y_train_2)
print(y_test_2)

X_train_2.shape : (32, 2), X_test_2.shape : (8, 2)
[0 1 0 0 1 0 1 0 1 0 0 1 0 0 0 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 0 0]
[0 0 0 0 0 1 1 1]


### ロジスティック回帰

In [17]:
clf_2 = make_pipeline(StandardScaler(),SGDClassifier(max_iter=1000, tol=1e-3,loss="log"))

# 学習する
clf_2.fit(X_train_2,y_train_2)
# 予測する
y_pred_clf_2 = clf_2.predict(X_test_2)

acc = metrics.accuracy_score(y_test_2, y_pred_clf_2)
precision = metrics.precision_score(y_test_2, y_pred_clf_2)
recall = metrics.recall_score(y_test_2, y_pred_clf_2)
f1 = metrics.f1_score(y_test_2, y_pred_clf_2)
confusion = metrics.confusion_matrix(y_test_2, y_pred_clf_2)

In [18]:
print("acc : {}".format(acc))
print("precision : {}".format(precision))
print("recall : {}".format(recall))
print("f1 : {}".format(f1))
print("confusion matrix \n {}".format(confusion))

acc : 0.375
precision : 0.375
recall : 1.0
f1 : 0.5454545454545454
confusion matrix 
 [[0 5]
 [0 3]]


### SVM

In [19]:
svc_2 = make_pipeline(StandardScaler(), SVC(gamma='auto'))

# 学習する
svc_2.fit(X_train_2,y_train_2)
# 予測する
y_pred_svc_2 = svc_2.predict(X_test_2)

print("acc : {}\nprecision : {}\nrecall : {}\nf1 : {}\nconfusion matrix \n {}".format(*eval(y_test_2, y_pred_svc_2)))


acc : 0.25
precision : 0.2
recall : 0.3333333333333333
f1 : 0.25
confusion matrix 
 [[1 4]
 [2 1]]


### 決定木

In [20]:
tree_2 = DecisionTreeClassifier(random_state=0)

# 学習する
tree_2.fit(X_train_2,y_train_2)
# 予測する
y_pred_tree_2 = tree_2.predict(X_test_2)

print("acc : {}\nprecision : {}\nrecall : {}\nf1 : {}\nconfusion matrix \n {}".format(*eval(y_test_2, y_pred_tree_2)))


acc : 0.375
precision : 0.25
recall : 0.3333333333333333
f1 : 0.28571428571428575
confusion matrix 
 [[2 3]
 [2 1]]


# 【問題3】 回帰問題を解くコードの作成

## 線形回帰でHouse Pricesデータセットを学習・推定

In [21]:
#モジュールをインポート」
from sklearn.linear_model import SGDRegressor

csv_path = "train.csv" # ファイル名（パス）を指定する

'''学習用データの読み込み'''
df = pd.read_csv("train_1.csv")
#print(df)

# 目的変数
y_3 = df.loc[:,["SalePrice"]]

#説明変数
X_3 = df.loc[:,["GrLivArea","YearBuilt"]]
X_1 = df.loc[:,["GrLivArea"]]
X_2 = df.loc[:,["YearBuilt"]]

In [22]:
X_train_3, X_test_3, y_train_3, y_test_3 = scratch_train_test_split(X_3,y_3,train_size=0.8)
print("X_train_3.shape : {}, X_test_3.shape : {}".format(X_train_3.shape, X_test_3.shape))
# print(y_train_3)
# print(y_test_3)

X_train_3.shape : (1168, 2), X_test_3.shape : (292, 2)


In [23]:
reg = make_pipeline(StandardScaler(),SGDRegressor(max_iter=1000, tol=1e-3))

# 学習する
reg.fit(X_train_3,y_train_3)
# 予測する
y_pred_reg = reg.predict(X_test_3)

from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

'''予測結果の確認'''
#決定係数を表示
print("MSE値 : % 0.3f" % mean_squared_error(y_test_3, y_pred_reg))
print("RMSE値 : % 0.3f" % mean_squared_error(y_test_3, y_pred_reg, squared=False))



MSE値 :  2369512602.556
RMSE値 :  48677.640
